### ISSUE TITLE
Bot code issue.

### ISSUE THREAD

**Issue by Dorian349** [LivelySource/DM-BOT#1]
Hey,

I see a lot of errors and mistake on the code. (Bot isn't working with the current code)
Can pull a request if you need it ^^
Just tell me ;)

Best Regards.

**Comment by LivelySource** [comment]
Thanks for your feedback, sorry for taking almost 2 years to respond. Good news though! There the code works great for what it's meant for,
https://i.imgur.com/Di5d7je.png
https://i.imgur.com/NzB9MJN.png
https://i.imgur.com/yEG5UeT.png

**Comment by Kyr4l** [comment]
> 
> 
> Thanks for your feedback, sorry for taking almost 2 years to respond. Good news though! There the code works great for what it's meant for,
> https://i.imgur.com/Di5d7je.png
> https://i.imgur.com/NzB9MJN.png
> https://i.imgur.com/yEG5UeT.png

i don't think it's really working properly, it the bot crashes every time i send an image to it via DM
