### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by BrendanDenzel** [LivelySource/DM-BOT#12]

**Comment by Mhankk** [comment]
you have to use your own bot token. see [here](https://discord.com/developers/docs/topics/oauth2) for details or just visit https://discord.com/developers/applications/ and open the Bot menu
![Bot Section](https://cdn.discordapp.com/attachments/571743243075584001/939785420370227220/22.png)
Then click copy token and paste on your `config.json` files
![Token Section](https://cdn.discordapp.com/attachments/571743243075584001/939785420621873182/Screenshot_from_2022-02-06_14-30-17.png)

**Comment by LivelySource** [comment]
Closed.
