### ISSUE TITLE
How to mention everyone??

### ISSUE THREAD

**Issue by reebenbg** [LivelySource/DM-BOT#2]
How can I mention every user from my server when I have to type ONE user ID?!?!?!

Thank you for the help

**Comment by HuskyCodez** [comment]
> How can I mention every user from my server when I have to type ONE user ID?!?!?!
> 
> Thank you for the help

You mean tag @everyone?, correct me if I’m wrong.

**Comment by LivelySource** [comment]
I'm not exactly sure what you mean ?

**Comment by LivelySource** [comment]
Closed.
